# Generated by Django 4.1.3 on 2022-11-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_alter_cargo_campanyname_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='CampanyName',
            field=models.CharField(choices=[('LINFOX', 'linfox'), ('OTHERS', 'others')], default='linfox', max_length=20),
        ),
    ]
