# Generated by Django 4.1.3 on 2022-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_alter_cargo_campanyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='CampanyName',
            field=models.CharField(choices=[('LINFOX', 'linfox'), ('OTHERS', 'others')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_status',
            field=models.CharField(choices=[('Cargo Available', 'Cargo Available'), ('Cargo Not Available', 'Cargo Not Available')], default='Carg', max_length=50),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='driverName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
